### ISSUE TITLE
cannot compete installation as it asks for wifi!!!! 

### ISSUE THREAD

**Issue by ale82to** [kakathic/Apktool-X#1]
I don't know if the problem is related to android 11 after installing i both tryed apktool d /storage/emulated/0/Download/w.apk -p /data/data/ru.maximoff.apktool/files/framework/ -o /storage/emulated/0/Download/w_src
and
 apktool d /storage/emulated/0/Download/w.apk -o /storage/emulated/0/Download/w_src
and I always get this long errror messaged Exception in thread "main" brut.androlib.AndrolibException: java.nio.file.NoSuchFileException: /system/app/miui/miui.apk
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.Androlib.installFramework(Androlib.java:707)
	at brut.apktool.Main.cmdInstallFramework(Main.java:269)
	at brut.apktool.Main.main(Main.java:82)
Caused by: java.nio.file.NoSuchFileException: /system/app/miui/miui.apk
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	... 5 more
Exception in thread "main" brut.androlib.AndrolibException: java.nio.file.NoSuchFileException: /system/app/miuisystem/miuisystem.apk
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.Androlib.installFramework(Androlib.java:707)
	at brut.apktool.Main.cmdInstallFramework(Main.java:269)
	at brut.apktool.Main.main(Main.java:82)
Caused by: java.nio.file.NoSuchFileException: /system/app/miuisystem/miuisystem.apk
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	... 5 more
Exception in thread "main" brut.androlib.AndrolibException: java.nio.file.NoSuchFileException: /system/framework/framework-ext-res/framework-ext-res.apk
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.Androlib.installFramework(Androlib.java:707)
	at brut.apktool.Main.cmdInstallFramework(Main.java:269)
	at brut.apktool.Main.main(Main.java:82)
Caused by: java.nio.file.NoSuchFileException: /system/framework/framework-ext-res/framework-ext-res.apk
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	... 5 more
Exception in thread "main" brut.androlib.AndrolibException: java.nio.file.NoSuchFileException: /system/priv-app/RtMiCloudSDK/RtMiCloudSDK.apk
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.Androlib.installFramework(Androlib.java:707)
	at brut.apktool.Main.cmdInstallFramework(Main.java:269)
	at brut.apktool.Main.main(Main.java:82)
Caused by: java.nio.file.NoSuchFileException: /system/priv-app/RtMiCloudSDK/RtMiCloudSDK.apk
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	... 5 more
Exception in thread "main" brut.androlib.AndrolibException: java.nio.file.NoSuchFileException: /system/priv-app/PersonalAssistant/PersonalAssistant.apk
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.res.AndrolibResources.installFramework(Unknown Source)
	at brut.androlib.Androlib.installFramework(Androlib.java:707)
	at brut.apktool.Main.cmdInstallFramework(Main.java:269)
	at brut.apktool.Main.main(Main.java:82)
Caused by: java.nio.file.NoSuchFileException: /system/priv-app/PersonalAssistant/PersonalAssistant.apk
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	... 5 more
Destination directory (/storage/emulated/0/Download/w_src) already exists. Use -f switch if you want to overwrite it.
my phone is a mi 10 Lite with arrow OS (lineage OS 18.1)

**Comment by kakathic** [comment]
No need to use -p
